services:
  app:
    build: .
    container_name: springboot-todo-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
    restart: unless-stopped

  db:
    image: mariadb:11.8.2
    container_name: mariadb-todo
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "2004:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mariadb -h 127.0.0.1 -u ${MYSQL_USER} -p${MYSQL_PASSWORD} -e 'USE ${MYSQL_DATABASE}'",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 180s

networks:
  backend:

volumes:
  db_data:
